# The NTSC-U release of SPPS (201.99) - Configuration for splat
name: SPPS 201-99 (US)
sha1: a299494580e009bca242d5a9773013fdb08d2fff
options:
  basename: SLUS_201.99
  target_path: ./config/SLUS_20199/SLUS_201.99
  platform: ps2
  compiler: MWCCPS2
  endianness: little

  base_path: ../../
  ld_script_path: ./config/SLUS_20199/out/SLUS_201.99.ld
  asm_path: ./config/SLUS_20199/out/asm
  asset_path: ./config/SLUS_20199/out/assets
  build_path: ./build
  src_path: ./src/SLUS_20199/

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: ./config/SLUS_20199/undefined_funcs_auto.yaml
  create_undefined_syms_auto: True
  undefined_syms_auto_path: ./config/SLUS_20199/undefined_syms_auto.yaml
  symbol_addrs_path: ./config/SLUS_20199/symbol_addresses.txt
  extensions_path: ./tools/splat_ext
  section_order: [".text", ".data", ".rodata", ".sdata", ".sbss", ".bss"]
  subalign: 8
  disasm_unknown: True
  named_regs_for_c_funcs: False
  use_legacy_include_asm: False
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  asm_inc_header: .set noat    /* allow use of $at register from MWCC */

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  find_file_boundaries: True
  pair_rodata_to_text: True
  auto_decompile_empty_functions: True
  do_c_func_detection: True
  suggestion_rodata_section_start: True
  migrate_rodata_to_functions: True

segments:
  - [0, databin, elf_header]
  - name: main
    type: code
    start: 0x0080
    vram: 0x100000
    gp_value: 0x2ef6f0
    bss_size: 0xE1F80 # (Comes from __bss_end -_fbss)
    subsegments:
      - [0x000080, pad, nops]
      - [0x000088, asm, _start]
      - [0x000138, asm, _exit]
      - [0x000140, asm, _root]
      - [0x028A70, c, E/tam/ps2/sppbx/main]
      - [0x029BE0, c, Z/ul/ul/source/cdvd]
      - [0x000150, asm, sdk]
      - [0x02A7E0, asm, Z/ul/ul/source/coord]
      - [0x02AAA0, asm, Z/ul/ul/source/gif]
      - [0x02ACA0, asm, Z/ul/ul/source/gifpkt]
      - [0x02B100, asm, Z/ul/ul/source/graph]
      - [0x02E200, asm, Z/ul/ul/source/heap]
      - [0x02E6B0, c, Z/ul/ul/source/mcard]
      - [0x0300E0, asm, Z/ul/ul/source/mdlpr]
      - [0x0304B0, asm, Z/ul/ul/source/mdlpra]
      - [0x030AB0, asm, Z/ul/ul/source/mdlprAmb]
      - [0x030E10, asm, Z/ul/ul/source/mdlprEnv]
      - [0x031200, asm, Z/ul/ul/source/mdlprHlt]
      - [0x031650, asm, Z/ul/ul/source/mdlprSdw]
      - [0x031980, asm, Z/ul/ul/source/model]
      - [0x032B00, asm, Z/ul/ul/source/pad]
      - [0x036010, asm, Z/ul/ul/source/sd]
      - [0x0365F0, asm, Z/ul/ul/source/sprintf]
      - [0x036FA0, asm, Z/ul/ul/source/system]
      - [0x037470, asm, Z/ul/ul/source/vif1]
      - [0x0374E0, asm, Z/ul/ul/source/mv2ext]
      - [0x03BE80, asm, Z/ul/ul/source/movie2]
      - [0x03CBD0, asm, Z/ul/ul/source/graph2]
      - [0x03D030, asm, Z/ul/ul/source/TEX]
      - [0x03F360, asm, Z/ul/ul/source/mdlprTon]
      - [0x03F940, asm, Z/ul/ul/source/vumodel] 
      - [0x041490, asm, Z/ul/ul/source/xmem]
      - [0x041B20, asm, Z/ul/ul/source/spr]
      - [0x041BF0, asm, Z/ul/ul/source/strconv]
      - [0x0420A0, asm, E/tam/ps2/sppbx/tmgraph]
      - [0x043660, asm, E/tam/ps2/sppbx/tmcrs]
      - [0x055FA0, asm, E/tam/ps2/sppbx/tmalpha]
      - [0x056340, asm, E/tam/ps2/sppbx/maanim]
      - [0x05DE00, asm, E/tam/ps2/sppbx/ktmot]
      - [0x063CA0, asm, E/tam/ps2/sppbx/ktact]
      - [0x0849A0, asm, E/tam/ps2/sppbx/nmfont]
      - [0x089380, c, E/tam/ps2/sppbx/ktmenu]
      - [0x089530, c, E/tam/ps2/sppbx/ktmnufnc]
      - [0x089860, c, E/tam/ps2/sppbx/spinit]
      - [0x08A680, asm, E/tam/ps2/sppbx/spload]
      - [0x0974C0, c, E/tam/ps2/sppbx/tmlink]
      - [0x097550, c, E/tam/ps2/sppbx/gmpad]
      - [0x097AD0, asm, E/tam/ps2/sppbx/ktrider]
      - [0x099020, asm, E/tam/ps2/sppbx/spfree]
      - [0x09FAA0, asm, E/tam/ps2/sppbx/tmevent]
      - [0x0A4310, asm, E/tam/ps2/sppbx/ayselect]
      - [0x0A4F80, asm, E/tam/ps2/sppbx/aycomfnk]
      - [0x0A7AD0, asm, E/tam/ps2/sppbx/aymcard]
      - [0x0B15B0, asm, E/tam/ps2/sppbx/aymodsel]
      - [0x0B4370, asm, E/tam/ps2/sppbx/aymovie]
      - [0x0B4E70, asm, E/tam/ps2/sppbx/aychrsel]
      - [0x0C24E0, asm, E/tam/ps2/sppbx/kncamera]
      - [0x0C75B0, asm, E/tam/ps2/sppbx/ayoption]
      - [0x0D6670, asm, E/tam/ps2/sppbx/nmvc]
      - [0x0D7910, asm, E/tam/ps2/sppbx/nmsnd]
      - [0x0D8CA0, asm, E/tam/ps2/sppbx/nmbgm]
      - [0x0D9D20, asm, E/tam/ps2/sppbx/nmsq]
      - [0x0DAE10, asm, E/tam/ps2/sppbx/nmdisp]
      - [0x10ED40, asm, E/tam/ps2/sppbx/nmdraw]
      - [0x114EA0, asm, E/tam/ps2/sppbx/knreplay]
      - [0x11B5E0, asm, E/tam/ps2/sppbx/spev01]
      - [0x126CE0, asm, E/tam/ps2/sppbx/ktsbcore]
      - [0x12AD80, asm, E/tam/ps2/sppbx/aycreate]
      - [0x133FC0, asm, E/tam/ps2/sppbx/akEffect]
      - [0x13AB50, asm, E/tam/ps2/sppbx/ayresult]
      - [0x149230, asm, E/tam/ps2/sppbx/spev04]
      - [0x15AC40, asm, E/tam/ps2/sppbx/tieffect]
      - [0x160630, asm, E/tam/ps2/sppbx/spev08]
      - [0x166070, asm, E/tam/ps2/sppbx/nmact]
      - [0x168B10, asm, E/tam/ps2/sppbx/spev02]
      - [0x173D60, asm, E/tam/ps2/sppbx/spev03]
      - [0x17B560, asm, E/tam/ps2/sppbx/spev06]
      - [0x183060, asm, E/tam/ps2/sppbx/spev07]
      - [0x18AC70, asm, E/tam/ps2/sppbx/spev05]
      - [0x194160, asm, E/tam/ps2/sppbx/kncore]
      - [0x1962A0, asm, E/tam/ps2/sppbx/nmevent]
      - [0x1966C0, asm, E/tam/ps2/sppbx/akEvEfct]
      - [0x19A610, asm, E/tam/ps2/sppbx/akSelEff]
      - [0x19B470, asm, E/tam/ps2/sppbx/akShadow]
      - [0x19C250, asm, E/tam/ps2/sppbx/nmtrick]
      - [0x1A1960, asm, E/tam/ps2/sppbx/tiutill]
      - [0x1A1E70, asm, E/tam/ps2/sppbx/akSpSub]
      - [0x1A2430, asm, E/tam/ps2/sppbx/tmetc]
      - [0x1A2D00, asm, E/tam/ps2/sppbx/tievent]
      # Library/SDK
      - [0x1A7600, databin, sdk2]
      - [0x1A8000, data, vutext] # .vutext 0x1A8000-0x1AF6AF

      # SDK/Lib data start
      - [0x1AF6B0, data, data_start]
      # SDK/Lib data end

      # Game data
      - [0x1B2E70, .data, E/tam/ps2/sppbx/main]
      - [0x1B2E80, data, Z/ul/ul/source/mdlpr]
      - [0x1B2EA0, data, Z/ul/ul/source/model]
      - [0x1B2F50, data, Z/ul/ul/source/movie2]
      - [0x1B2F70, data, Z/ul/ul/source/strconv]
      - [0x1B2FA0, data, E/tam/ps2/sppbx/tmgraph]
      - [0x1B2FE0, data, E/tam/ps2/sppbx/tmcrs]
      - [0x1B3050, data, E/tam/ps2/sppbx/maanim]
      - [0x1B3100, data, E/tam/ps2/sppbx/ktmot]
      - [0x1B5130, data, E/tam/ps2/sppbx/ktact]
      - [0x1B5880, .data, E/tam/ps2/sppbx/ktmnufnc]
      - [0x1B5900, .data, E/tam/ps2/sppbx/spinit]
      - [0x1B8030, data, E/tam/ps2/sppbx/spload]
      - [0x1B8600, data, E/tam/ps2/sppbx/ktrider]
      - [0x1B8620, data, E/tam/ps2/sppbx/spfree]
      - [0x1B8630, data, E/tam/ps2/sppbx/tmevent]
      - [0x1B8810, data, E/tam/ps2/sppbx/aycomfnk]
      - [0x1C7E20, data, E/tam/ps2/sppbx/aymcard]
      - [0x1CC8E0, data, E/tam/ps2/sppbx/aymodsel]
      - [0x1CC9F0, data, E/tam/ps2/sppbx/aymovie]
      - [0x1CCB20, data, E/tam/ps2/sppbx/aychrsel]
      - [0x1CCE80, data, E/tam/ps2/sppbx/kncamera]
      - [0x1CCED0, data, E/tam/ps2/sppbx/ayoption]
      - [0x1CD300, data, E/tam/ps2/sppbx/nmbgm]
      - [0x1CDA00, data, E/tam/ps2/sppbx/nmdisp]
      - [0x1CED80, data, E/tam/ps2/sppbx/nmdraw]
      - [0x1CEEC0, data, E/tam/ps2/sppbx/knreplay]
      - [0x1CF0C0, data, E/tam/ps2/sppbx/spev01]
      - [0x1CFBF0, data, E/tam/ps2/sppbx/ktsbcore]
      - [0x1CFC40, data, E/tam/ps2/sppbx/aycreate]
      - [0x1D0590, data, E/tam/ps2/sppbx/akEffect]
      - [0x1D05B0, data, E/tam/ps2/sppbx/ayresult]
      - [0x1D0AF0, data, E/tam/ps2/sppbx/spev04]
      - [0x1D1500, data, E/tam/ps2/sppbx/tieffect]
      - [0x1D17B0, data, E/tam/ps2/sppbx/spev08]
      - [0x1D2040, data, E/tam/ps2/sppbx/spev02]
      - [0x1D2580, data, E/tam/ps2/sppbx/spev03]
      - [0x1D32B0, data, E/tam/ps2/sppbx/spev06]
      - [0x1D3E10, data, E/tam/ps2/sppbx/spev07]
      - [0x1D5E50, data, E/tam/ps2/sppbx/spev05]
      - [0x1D6BD0, data, E/tam/ps2/sppbx/kncore]
      - [0x1D6BF0, data, E/tam/ps2/sppbx/akEvEfct]
      - [0x1D6C30, data, E/tam/ps2/sppbx/akSelEff]
      - [0x1D6C50, data, E/tam/ps2/sppbx/akShadow]
      - [0x1D6DC0, data, E/tam/ps2/sppbx/tiutill]
      - [0x1D6F50, data, E/tam/ps2/sppbx/tievent]
      # data end

      # rodata start
      - [0x1D7210, rodata, sdk_rodata]
      - [0x1D9540, .rodata, E/tam/ps2/sppbx/main]
      - [0x1D96F0, .rodata, Z/ul/ul/source/cdvd]
      - [0x1D9700, rodata, Z/ul/ul/source/heap]
      - [0x1D9830, .rodata, Z/ul/ul/source/mcard]
      - [0x1D9870, rodata, Z/ul/ul/source/sprintf]
      - [0x1D98F0, rodata, Z/ul/ul/source/system]
      - [0x1D99C0, rodata, Z/ul/ul/source/mv2ext]
      - [0x1D9B50, rodata, Z/ul/ul/source/movie2]
      - [0x1D9B70, rodata, Z/ul/ul/source/graph2]
      - [0x1D9BD0, rodata, Z/ul/ul/source/mdlprTon]
      - [0x1D9BE0, rodata, Z/ul/ul/source/vumodel]
      - [0x1D9C00, rodata, E/tam/ps2/sppbx/tmcrs]
      - [0x1D9D00, rodata, E/tam/ps2/sppbx/maanim]
      - [0x1D9D20, rodata, E/tam/ps2/sppbx/ktmot]
      - [0x1DA260, rodata, E/tam/ps2/sppbx/ktact]
      # border from normal$406 to f_arrange$411 is unclear between ktact and ktmnufnc
      - [0x1DAB00, .rodata, E/tam/ps2/sppbx/ktmnufnc]
      - [0x1DAB48, .rodata, E/tam/ps2/sppbx/spinit]
      # border from @12 to @650 unclear
      - [0x1DDDC0, rodata, E/tam/ps2/sppbx/spload]
      - [0x1DE8E0, rodata, E/tam/ps2/sppbx/ktrider]
      - [0x1DE900, rodata, E/tam/ps2/sppbx/spfree]
      - [0x1DE950, rodata, E/tam/ps2/sppbx/tmevent]
      - [0x1DE970, rodata, E/tam/ps2/sppbx/aycomfnk]
      - [0x1DEAB8, .rodata, E/tam/ps2/sppbx/aymcard]
      - [0x1DEFD0, rodata, E/tam/ps2/sppbx/aymodsel]
      - [0x1DF050, rodata, E/tam/ps2/sppbx/aymovie]
      # border of aymovie and aychrsel is unclear between @33 and @34
      - [0x1DF8C0, rodata, E/tam/ps2/sppbx/aychrsel]
      - [0x1DFFE8, rodata, E/tam/ps2/sppbx/ayoption]
      - [0x1E0B60, rodata, E/tam/ps2/sppbx/nmvc]
      - [0x1E0BA0, rodata, E/tam/ps2/sppbx/nmsnd]
      - [0x1E0E60, rodata, E/tam/ps2/sppbx/nmbgm]
      - [0x1E0F80, rodata, E/tam/ps2/sppbx/nmsq]
      - [0x1E10A8, rodata, E/tam/ps2/sppbx/nmdisp]
      - [0x1E3F88, rodata, E/tam/ps2/sppbx/nmdraw]
      - [0x1E4120, rodata, E/tam/ps2/sppbx/knreplay]
      - [0x1E4330, rodata, E/tam/ps2/sppbx/spev01]
      - [0x1E43B0, rodata, E/tam/ps2/sppbx/aycreate]
      - [0x1E4E80, rodata, E/tam/ps2/sppbx/akEffect]
      - [0x1E5140, rodata, E/tam/ps2/sppbx/ayresult]
      - [0x1E5CE0, rodata, E/tam/ps2/sppbx/spev04]
      - [0x1E5EE0, rodata, E/tam/ps2/sppbx/spev08]
      - [0x1E64E0, rodata, E/tam/ps2/sppbx/nmact]
      - [0x1E67C0, rodata, E/tam/ps2/sppbx/spev02]
      - [0x1E6900, rodata, E/tam/ps2/sppbx/spev03]
      - [0x1E6960, rodata, E/tam/ps2/sppbx/spev06]
      - [0x1E7410, rodata, E/tam/ps2/sppbx/spev07]
      - [0x1E7450, rodata, E/tam/ps2/sppbx/kncore]
      - [0x1E7490, rodata, E/tam/ps2/sppbx/nmevent]
      - [0x1E74B0, rodata, E/tam/ps2/sppbx/akEvEfct]
      - [0x1E74D0, rodata, E/tam/ps2/sppbx/nmtrick]
      - [0x1E75F0, rodata, end_rodata]
      # - [0x1E7704, databin] # __data_end
      # rodata end

      # sdata section
      # sdata is after __data_end

      - [0x1E7780, .sdata, E/tam/ps2/sppbx/main]
      - [0x1E7790, sdata, Z/ul/ul/source/pad]
      - [0x1E7798, sdata, Z/ul/ul/source/mv2ext]
      - [0x1E779C, sdata, E/tam/ps2/sppbx/ktact]
      - [0x1E7848, .sdata, E/tam/ps2/sppbx/ktmnufnc]
      - [0x1E7868, sdata, E/tam/ps2/sppbx/spload]
      - [0x1E7870, sdata, E/tam/ps2/sppbx/spfree]
      - [0x1E7874, sdata, E/tam/ps2/sppbx/aymcard]
      - [0x1E7878, sdata, E/tam/ps2/sppbx/aychrsel]
      - [0x1E7890, sdata, E/tam/ps2/sppbx/kncamera]
      - [0x1E78BC, sdata, E/tam/ps2/sppbx/ayoption]
      - [0x1E78C8, sdata, E/tam/ps2/sppbx/nmdisp]
      - [0x1E78E8, sdata, E/tam/ps2/sppbx/nmdraw]
      - [0x1E78F8, sdata, E/tam/ps2/sppbx/knreplay]
      - [0x1E7900, sdata, E/tam/ps2/sppbx/spev01]
      - [0x1E7918, sdata, E/tam/ps2/sppbx/ayresult]
      - [0x1E7924, sdata, E/tam/ps2/sppbx/tieffect]
      - [0x1E7960, sdata, E/tam/ps2/sppbx/spev02]
      - [0x1E7970, sdata, E/tam/ps2/sppbx/spev03]
      - [0x1E7980, sdata, E/tam/ps2/sppbx/spev07]
      - [0x1E7998, sdata, E/tam/ps2/sppbx/spev05]
      - [0x1E79A0, sdata, E/tam/ps2/sppbx/kncore]
      - [0x1E79B4, sdata, E/tam/ps2/sppbx/tiutill]
      - [0x1E79B8, sdata, E/tam/ps2/sppbx/tievent]
      # sdata right before sbss

      # Sbss section (Same location as _fbss)
      - { type: .sbss, vram: 0x2E7980, name: E/tam/ps2/sppbx/main } # 1E7A00
      - { type: .sbss, vram: 0x2e79d0, name: Z/ul/ul/source/cdvd }
      - { type: sbss, vram: 0x2e79d8, name: Z/ul/ul/source/coord }
      - { type: sbss, vram: 0x2e79e0, name: Z/ul/ul/source/pad }
      - { type: sbss, vram: 0x2e79f4, name: Z/ul/ul/source/sd }
      - { type: sbss, vram: 0x2e7a00, name: Z/ul/ul/source/system }
      - { type: sbss, vram: 0x2e7a04, name: Z/ul/ul/source/mv2ext }
      - { type: sbss, vram: 0x2e7a20, name: Z/ul/ul/source/movie2 }
      - { type: sbss, vram: 0x2e7a30, name: Z/ul/ul/source/TEX }
      - { type: sbss, vram: 0x2e7a38, name: E/tam/ps2/sppbx/ktact }
      - { type: sbss, vram: 0x2e7af0, name: E/tam/ps2/sppbx/nmfont }
      - { type: .sbss, vram: 0x2e7af4, name: E/tam/ps2/sppbx/ktmenu }
      - { type: .sbss, vram: 0x2e7b04, name: E/tam/ps2/sppbx/spinit }
      - { type: sbss, vram: 0x2e7b18, name: E/tam/ps2/sppbx/spload }
      - { type: .sbss, vram: 0x2e7b20, name: E/tam/ps2/sppbx/gmpad }
      - { type: sbss, vram: 0x2e7b40, name: E/tam/ps2/sppbx/spfree }
      - { type: sbss, vram: 0x2e7b88, name: E/tam/ps2/sppbx/tmevent }
      - { type: sbss, vram: 0x2e7bb4, name: E/tam/ps2/sppbx/ayselect }
      - { type: sbss, vram: 0x2e7bbc, name: E/tam/ps2/sppbx/aymcard }
      - { type: sbss, vram: 0x2e7bc8, name: E/tam/ps2/sppbx/aymodsel }
      - { type: sbss, vram: 0x2e7bd8, name: E/tam/ps2/sppbx/aymovie }
      - { type: sbss, vram: 0x2e7be4, name: E/tam/ps2/sppbx/aychrsel }
      - { type: sbss, vram: 0x2e7be8, name: E/tam/ps2/sppbx/kncamera }
      - { type: sbss, vram: 0x2e7bf8, name: E/tam/ps2/sppbx/ayoption }
      - { type: sbss, vram: 0x2e7bfc, name: E/tam/ps2/sppbx/nmvc }
      - { type: sbss, vram: 0x2e7c00, name: E/tam/ps2/sppbx/nmbgm }
      - { type: sbss, vram: 0x2e7c0c, name: E/tam/ps2/sppbx/nmsq }
      - { type: sbss, vram: 0x2e7c38, name: E/tam/ps2/sppbx/nmdisp }
      - { type: sbss, vram: 0x2e7eb0, name: E/tam/ps2/sppbx/knreplay }
      - { type: sbss, vram: 0x2e7ec0, name: E/tam/ps2/sppbx/spev01 }
      - { type: sbss, vram: 0x2e7f14, name: E/tam/ps2/sppbx/aycreate }
      - { type: sbss, vram: 0x2e7f18, name: E/tam/ps2/sppbx/akEffect }
      - { type: sbss, vram: 0x2e7f1c, name: E/tam/ps2/sppbx/ayresult }
      - { type: sbss, vram: 0x2e7f20, name: E/tam/ps2/sppbx/spev04 }
      - { type: sbss, vram: 0x2e7f8c, name: E/tam/ps2/sppbx/tieffect }
      - { type: sbss, vram: 0x2e7f90, name: E/tam/ps2/sppbx/spev08 }
      - { type: sbss, vram: 0x2e7f94, name: E/tam/ps2/sppbx/nmact }
      - { type: sbss, vram: 0x2e7fc8, name: E/tam/ps2/sppbx/spev02 }
      - { type: sbss, vram: 0x2e8028, name: E/tam/ps2/sppbx/spev03 }
      - { type: sbss, vram: 0x2e805c, name: E/tam/ps2/sppbx/spev06 }
      - { type: sbss, vram: 0x2e8060, name: E/tam/ps2/sppbx/spev07 }
      - { type: sbss, vram: 0x2e8080, name: E/tam/ps2/sppbx/spev05 }
      - { type: sbss, vram: 0x2e80c8, name: E/tam/ps2/sppbx/nmevent }
      - { type: sbss, vram: 0x2e80cc, name: E/tam/ps2/sppbx/nmtrick }

      # Bss section (Same location as __bss_start)
      - { type: bss, vram: 0x2E80DC, name: sdk }
      - { type: .bss, vram: 0x2eea90, name: E/tam/ps2/sppbx/main }
      - { type: .bss, vram: 0x2ef2e0, name: Z/ul/ul/source/cdvd }
      - { type: bss, vram: 0x2f2350, name: Z/ul/ul/source/coord }
      - { type: bss, vram: 0x2f23d0, name: Z/ul/ul/source/heap }
      - { type: .bss, vram: 0x2f2400, name: Z/ul/ul/source/mcard }
      - { type: bss, vram: 0x2f3350, name: Z/ul/ul/source/pad }
      - { type: bss, vram: 0x2f3850, name: Z/ul/ul/source/sd }
      - { type: bss, vram: 0x2f3a50, name: Z/ul/ul/source/system }
      - { type: bss, vram: 0x2f3db0, name: Z/ul/ul/source/mv2ext }
      - { type: bss, vram: 0x2f3f40, name: Z/ul/ul/source/movie2 }
      - { type: bss, vram: 0x2f4740, name: E/tam/ps2/sppbx/tmcrs }
      - { type: bss, vram: 0x307ec0, name: E/tam/ps2/sppbx/ktact }
      - { type: bss, vram: 0x346f70, name: E/tam/ps2/sppbx/nmfont }
      - { type: .bss, vram: 0x347010, name: E/tam/ps2/sppbx/ktmenu }
      - { type: .bss, vram: 0x3473d0, name: E/tam/ps2/sppbx/spinit }
      - { type: bss, vram: 0x3a4640, name: E/tam/ps2/sppbx/spload }
      - { type: .bss, vram: 0x3bd360, name: E/tam/ps2/sppbx/gmpad }
      - { type: bss, vram: 0x3bd480, name: E/tam/ps2/sppbx/ktrider }
      - { type: bss, vram: 0x3bd4a0, name: E/tam/ps2/sppbx/spfrees }
      - { type: bss, vram: 0x3bfd30, name: E/tam/ps2/sppbx/tmevent }
      - { type: bss, vram: 0x3c0be0, name: E/tam/ps2/sppbx/aymodsel }
      - { type: bss, vram: 0x3c0c40, name: E/tam/ps2/sppbx/aychrsel }
      - { type: bss, vram: 0x3c0ca0, name: E/tam/ps2/sppbx/kncamera }
      - { type: bss, vram: 0x3c0f00, name: E/tam/ps2/sppbx/nmvc }
      - { type: bss, vram: 0x3c27f0, name: E/tam/ps2/sppbx/nmbgm }
      - { type: bss, vram: 0x3c2840, name: E/tam/ps2/sppbx/nmsq }
      - { type: bss, vram: 0x3c2ab0, name: E/tam/ps2/sppbx/nmdisp }
      - { type: bss, vram: 0x3c6a30, name: E/tam/ps2/sppbx/nmdraw }
      - { type: bss, vram: 0x3c6a50, name: E/tam/ps2/sppbx/knreplay }
      - { type: bss, vram: 0x3c6e00, name: E/tam/ps2/sppbx/spev01 }
      - { type: bss, vram: 0x3c70e0, name: E/tam/ps2/sppbx/spev04 }
      - { type: bss, vram: 0x3c7430, name: E/tam/ps2/sppbx/spev08 }
      - { type: bss, vram: 0x3c7520, name: E/tam/ps2/sppbx/spev02 }
      - { type: bss, vram: 0x3c7870, name: E/tam/ps2/sppbx/spev03 }
      - { type: bss, vram: 0x3c78e0, name: E/tam/ps2/sppbx/spev07 }
      - { type: bss, vram: 0x3c7ad0, name: E/tam/ps2/sppbx/spev05 }
      - { type: bss, vram: 0x3c8010, name: E/tam/ps2/sppbx/nmevent }
      - { type: bss, vram: 0x3c8110, name: E/tam/ps2/sppbx/akEvEfct }
      - { type: bss, vram: 0x3c8840, name: E/tam/ps2/sppbx/nmtrick }
      - { type: bss, vram: 0x3c9860, name: E/tam/ps2/sppbx/tmetc }
      - { type: bss, vram: 0x3C9900, name: vubss } # 2C9980
      # - [1E7A00, databin] # after @771
  - [0x1E7A00, databin, end]
  - [0x58653C]