_dpflt = 0x100110;
_dpfgt = 0x100130;
sceGsResetGraph = 0x100150;
sceGsResetPath = 0x1002F0;
sceGsSetDefClear = 0x100938;
sceGsSyncV = 0x100B28;
sceGsSyncPath = 0x100BC0;
sceGsSetDefLoadImage = 0x100ED8;
sceGsSetDefStoreImage = 0x1010C0;
sceGsExecLoadImage = 0x101200;
sceGsExecStoreImage = 0x101380;
sceGsSetHalfOffset = 0x101A10;
sceGsSetHalfOffset2 = 0x101C78;
sceGsSetDefDBuffDc = 0x101D00;
sceGsSwapDBuffDc = 0x101FE8;
sceDmaGetChan = 0x102080;
sceDmaReset = 0x1020A8;
sceDmaPutEnv = 0x102198;
sceDmaGetEnv = 0x102370;
sceDmaSend = 0x1023D0;
sceDmaSendN = 0x1024A8;
sceDmaRecvN = 0x102740;
sceDmaSync = 0x102920;
sceGifPkInit = 0x102B18;
sceGifPkReset = 0x102B28;
sceGifPkTerminate = 0x102B38;
sceGifPkCnt = 0x102B90;
sceGifPkRef = 0x102C08;
sceGifPkEnd = 0x102CA0;
sceGifPkReserve = 0x102D18;
sceGifPkOpenGifTag = 0x102D30;
sceGifPkCloseGifTag = 0x102D48;
sceGifPkAddGsAD = 0x102DF0;
sceGifPkRefLoadImage = 0x102E18;
sceVif1PkInit = 0x102FD8;
sceVif1PkReset = 0x102FE8;
sceVif1PkTerminate = 0x102FF8;
sceVif1PkCnt = 0x103050;
sceVif1PkRef = 0x1030A8;
sceVif1PkCall = 0x103140;
sceVif1PkEnd = 0x1031B0;
sceVif1PkOpenDirectCode = 0x103208;
sceVif1PkCloseDirectCode = 0x103260;
sceVif1PkReserve = 0x103350;
sceVif1PkAlign = 0x103368;
sceVif1PkAddCode = 0x1033E8;
sceVif1PkRefLoadImage = 0x103430;
sceVif1PkOpenDirectHLCode = 0x103618;
sceVif1PkCloseDirectHLCode = 0x103670;
sceVu0ApplyMatrix = 0x1036A0;
sceVu0MulMatrix = 0x1036D0;
sceVu0OuterProduct = 0x103718;
sceVu0InnerProduct = 0x103738;
sceVu0Normalize = 0x103760;
sceVu0TransposeMatrix = 0x103798;
sceVu0InversMatrix = 0x1037E0;
sceVu0DivVector = 0x103850;
sceVu0DivVectorXYZ = 0x103870;
sceVu0InterVector = 0x103890;
sceVu0AddVector = 0x1038B8;
sceVu0SubVector = 0x1038D0;
sceVu0MulVector = 0x1038E8;
sceVu0ScaleVector = 0x103900;
sceVu0TransMatrix = 0x103918;
sceVu0CopyVector = 0x103948;
sceVu0CopyMatrix = 0x103958;
sceVu0FTOI4Vector = 0x103980;
sceVu0FTOI0Vector = 0x103990;
sceVu0UnitMatrix = 0x1039C0;
sceVu0RotMatrixZ = 0x103A60;
sceVu0RotMatrixX = 0x103B08;
sceVu0RotMatrixY = 0x103BB0;
sceVu0RotMatrix = 0x103C58;
sceVu0CameraMatrix = 0x103CD0;
sceVu0NormalLightMatrix = 0x103D80;
sceVu0LightColorMatrix = 0x103E40;
sceVu0ViewScreenMatrix = 0x103EA8;
sceVu0InterVectorXYZ = 0x104200;
sceVu0ScaleVectorXYZ = 0x104230;
sceVpu0Reset = 0x104380;
_rix_000 = 0x105378;
_ri0_000 = 0x1053F0;
_rix_001 = 0x105488;
_ri0_001 = 0x105540;
_rix_010 = 0x105610;
_ri0_010 = 0x1056C0;
_rix_011 = 0x105778;
_ri0_011 = 0x105870;
_rix_100 = 0x105970;
_ri0_100 = 0x105A18;
_rix_101 = 0x105AC8;
_ri0_101 = 0x105BB0;
_rix_110 = 0x105C98;
_ri0_110 = 0x105D78;
_rix_111 = 0x105E48;
_ri0_111 = 0x105F70;
_pictureCodingExtension = 0x107E18;
_quantMatrixExtension = 0x108248;
_pictureDisplayExtension = 0x1082F8;
_copyrightExtension = 0x1083E8;
sceMpegDemuxPssRing = 0x109D00;
sceMpegAddStrCallback = 0x10A010;
sceMpegInit = 0x10A850;
sceMpegCreate = 0x10A8F0;
sceMpegDelete = 0x10AB30;
sceMpegGetPicture = 0x10AB70;
sceMpegIsEnd = 0x10AC88;
sceMpegIsRefBuffEmpty = 0x10AC98;
sceMpegReset = 0x10ACA8;
sceMpegAddCallback = 0x10AD50;
_sequenceExtension = 0x10BDA8;
_sequenceDisplayExtension = 0x10BF10;
_sequenceScalableExtension = 0x10BFB0;
_unknown_extension = 0x10BFC0;
_pictureSpatialScalableExtension = 0x10BFD0;
_pictureTemporalScalableExtension = 0x10BFE0;
Exit = 0x10C680;
AddIntcHandler = 0x10C740;
RemoveIntcHandler = 0x10C760;
AddDmacHandler = 0x10C770;
RemoveDmacHandler = 0x10C790;
CreateThread = 0x10C860;
DeleteThread = 0x10C870;
StartThread = 0x10C880;
TerminateThread = 0x10C8B0;
RotateThreadReadyQueue = 0x10C910;
GetThreadId = 0x10C950;
CreateSema = 0x10CA60;
DeleteSema = 0x10CA70;
SignalSema = 0x10CA80;
WaitSema = 0x10CAA0;
FlushCache = 0x10CCE0;
sceSifDmaStat = 0x10CE00;
sceSifSetDma = 0x10CE20;
DisableIntc = 0x10D488;
EnableIntc = 0x10D4F0;
DisableDmac = 0x10D558;
EnableDmac = 0x10D5C0;
kCopy = 0x10D6C8;
serialPutchar = 0x10E330;
scePrintf = 0x10EB60;
sceSifInitRpc = 0x10F308;
sceSifBindRpc = 0x10F978;
sceSifCallRpc = 0x10FB48;
sceSifCheckStatRpc = 0x10FD38;
sceFsReset = 0x110B28;
sceOpen = 0x110B60;
sceClose = 0x110DE8;
sceRead = 0x1111A0;
sceWrite = 0x111410;
sceSifInitIopHeap = 0x1138F0;
sceSifAllocIopHeap = 0x113978;
sceSifFreeIopHeap = 0x113AE0;
sceSifLoadFileReset = 0x113D80;
sceSifLoadModule = 0x1145F0;
sceSifSyncIop = 0x114AB8;
sceSifRebootIop = 0x114AF0;
DIntr = 0x114C00;
EIntr = 0x114C48;
_InitSys = 0x114CA8;
scePadInit = 0x114E00;
scePadPortOpen = 0x115060;
scePadRead = 0x1153B0;
scePadGetState = 0x115430;
scePadGetReqState = 0x115548;
scePadInfoAct = 0x1155D0;
scePadInfoMode = 0x115810;
scePadSetMainMode = 0x115948;
scePadSetActDirect = 0x115A00;
scePadSetActAlign = 0x115AB8;
scePadInfoPressMode = 0x115CF8;
scePadEnterPressMode = 0x115D58;
scePadExitPressMode = 0x115DB0;
sceCdSearchFile = 0x116668;
sceCdSync = 0x116B70;
sceCdInit = 0x116DF0;
sceCdDiskReady = 0x1170D0;
sceCdMmode = 0x1172C8;
sceCdGetReadPos = 0x117390;
sceCdRead = 0x1173C0;
sceCdReadIOPm = 0x1175A0;
sceCdGetDiskType = 0x1176F8;
sceCdGetError = 0x117790;
sceCdBreak = 0x117828;
sceCdReadClock = 0x1178E0;
sceCdStInit = 0x1179D8;
sceCdStStart = 0x117A08;
sceCdStStop = 0x117AA0;
sceCdStRead = 0x117AD8;
sceMcInit = 0x117EB8;
sceMcOpen = 0x118218;
sceMcMkdir = 0x118350;
sceMcClose = 0x118388;
sceMcSeek = 0x118440;
sceMcRead = 0x1185A8;
sceMcWrite = 0x1186C8;
sceMcSync = 0x1188B8;
sceMcGetInfo = 0x1189F0;
sceMcGetDir = 0x118B78;
sceMcChdir = 0x118D58;
sceMcFormat = 0x118EA8;
sceMcDelete = 0x118F70;
sceMcSetFileInfo = 0x119150;
sceMcRename = 0x119328;
sceMcUnformat = 0x119490;
sceSdRemoteInit = 0x119670;
sceSdRemote = 0x1197B0;
sceDevVu0Reset = 0x119980;
sceDevVu1Reset = 0x119E30;
sceDevGifReset = 0x11A2D0;
sceDevVif0Reset = 0x11A588;
sceDevVif1Reset = 0x11A8B8;
fabs = 0x11CE60;
cosf = 0x11D218;
fabsf = 0x11D300;
sinf = 0x11D590;
tanf = 0x11D680;
atan2 = 0x11D708;
acosf = 0x11D820;
atan2f = 0x11D920;
sqrtf = 0x11DA48;
abs = 0x11DB80;
memcpy = 0x120C00;
memset = 0x120DB8;
printf = 0x121EE8;
srand = 0x121F38;
rand = 0x121F48;
strcat = 0x122650;
strcmp = 0x122780;
strlen = 0x1229E0;
__fixsfdi = 0x125BA0;
__fixunssfdi = 0x125CD0;
__muldi3 = 0x1265A8;
__udivdi3 = 0x126608;
__umoddi3 = 0x126BD8;
dpadd = 0x127528;
dpmul = 0x1275E8;
litodp = 0x127B60;
dptoli = 0x127C18;
dptofp = 0x127DB8;
fptosi = 0x128820;
fptoui = 0x1288B0;
fptodp = 0x1289B0;
sceScfGetDateNotation = 0x2A77C8;
sceScfGetTimeNotation = 0x2A78C8;
sceScfGetLocalTimefromRTC = 0x2A7EC8;
